### ISSUE TITLE
KeyPad

### ISSUE THREAD

**Issue by tmastersmart** [birdslikewires/hubitat#10]
Im trying to send the state to the iris v1 keypad. Im running into trouble formatting the command
Using your code I have been able to decode and act on all the info it sends to Receive PINS and arm
What I need to figure out the chime and arm commands so the lights will work right.

Not sure if you have seen this source code links bellow.
It says to send the command on the same cluster as data is received which is 00C0
sendZigbeeCommands(["he raw ${device.deviceNetworkId} 0 ${device.endpointId} 0x00C0 02 {11 00 01 01 01} {0xC216}"])
sends Cluster:00C0 command:01 MAP:[01, 00, 86] back to me
{11 10 00 00 01} sends back Cluster:00C0 command:01  [00, 01, 00, 18, 00, 00, 01, 00, 18, 00]

Cluster:00C0 command:00 MAP:[20, 00] Gets resent over and over I suspect 20 is mode and 0 is off.

Can you offer any help on formatting the command to send to the pad. I noticed you dont have cluster 00C0 in any of your docs.

https://github.com/arcus-smart-home/arcusplatform/blob/a02ad0e9274896806b7d0108ee3644396f3780ad/platform/arcus-containers/driver-services/src/main/resources/ZB_AlertMe_KeyPad_2_4.driver

https://github.com/arcus-smart-home/arcusplatform/blob/a02ad0e9274896806b7d0108ee3644396f3780ad/agent/arcus-reflex-controller/src/main/java/com/iris/agent/reflex/drivers/AlertmeKeyPad.java

https://github.com/arcus-smart-home/arcusplatform/blob/a02ad0e9274896806b7d0108ee3644396f3780ad/common/arcus-protocol/src/main/irp/ame-general.irp

**Comment by andydvsn** [comment]
I'm not sure I can help on this one, as my information is based upon that which was sniffed from traffic on the AlertMe system in the UK, which unfortunately never had a keypad. The Arcus code is probably the best pointer you will find. I've read recently that somebody has indeed got a driver for the Iris keypad working - is this you? :)
