### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by dr-luffe** [birdslikewires/hubitat#13]
Sorry to bother you. I have an issue with updateting the "Ikea symfonisk and tradfri driver". Getting this error when I try to update: 

"An error occurred while installing the package: Failed to upgrade driver https://raw.githubusercontent.com/birdslikewires/hubitat/master/ikea/drivers/ikea_tradfri_shortcut_button_e1812.groovy."

If I remove the dot at the end I find the code copies it and put it in as drivercode.

<img width="865" alt="Skærmbillede 2022-03-07 kl  12 11 29" src="https://user-images.githubusercontent.com/101107668/157020476-7a5740ef-6367-450e-b24d-0027d1be39f0.png">

<img width="1452" alt="Skærmbillede 2022-03-07 kl  12 12 33" src="https://user-images.githubusercontent.com/101107668/157020645-e9b04809-0aa2-4c79-9dec-4f63dbd42d6a.png">

Please advise

Regards
Kim

**Comment by andydvsn** [comment]
I have no idea on this one, I think the '.' is being added by HPM. I can't replicate the problem here and hopefully the months and months before I spotted this have led to a resolution. ;)
