### ISSUE TITLE
Package Updater drops error on Xiaomi drivers

### ISSUE THREAD

**Issue by ispgeek** [birdslikewires/hubitat#16]
Have been getting this error for months now when trying to update.  Thought it would get caught sooner but apparently I'm the only one using these devices lol.  

Error Occurred During Installation
An error occurred while installing the package: Failed to upgrade driver https://raw.githubusercontent.com/birdslikewires/hubitat/master/xiaomi/drivers/xiaomi_aqara_temperature_humidity_sensor_wsdcgq11lm.groovy.

**Comment by andydvsn** [comment]
You need the latest version of HPM. Only 1.8.7 or later knows how to install libraries properly. Update HPM first, then you should be good to go.
